# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy project files
COPY . .

# Upgrade pip and install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir httpx>=0.28.1 mcp[cli]>=1.6.0 plexapi>=4.16.1

# Expose port if needed (not used for stdio transport)

# Run the MCP server
CMD ["python", "plex-mcp.py"]
