# .github/workflows/ci.yml
name: CI

on:
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run unit tests
        run: pytest
